

INSERT INTO STUDENTS (FIRST_NAME, LAST_NAME, EMAIL)   
    VALUES ('Sabrina', 'Holene', 'snholene@my.waketech.edu'); 

INSERT INTO ASSIGNMENTS (TITLE, DESCRIPTION, DUE_DATE, STUDENT_ID) 
VALUES ('LAB7 POSTGRES', 'SET UP A DATABASE AND INSERT RECORDS AS DESCRIBED IN THE INSTRUCTIONS.','2025-03-14', 1);


SELECT * FROM ASSIGNMENTS, STUDENTS WHERE ASSIGNMENTS.STUDENT_ID = STUDENTS.STUDENT_ID
